In [20]:
import sys
import numpy as np

In [21]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [22]:
a = np.array([1, 2, 3, 4])

In [23]:
b = np.array([0, -5, 1, 1.5, 2])

In [34]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [25]:
a[0:]

array([1, 2, 3, 4])

In [26]:
a[1:3]

array([2, 3])

In [27]:
a[1:-1]

array([2, 3])

In [28]:
a[::2]

array([1, 3])

In [29]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [30]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [31]:
b[[0, 2, -1]]

array([0., 1., 2.])

Array Types

In [32]:
a.dtype

dtype('int64')

In [35]:
b.dtype

dtype('float64')

In [38]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [40]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [42]:
c.dtype

dtype('<U1')

dtype('O') -> object

In [43]:
d = np.array([{'a': 1}, sys])

In [44]:
d.dtype

dtype('O')

Dimensions and shapes

In [45]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [46]:
A.shape

(2, 3)

In [47]:
A.ndim

2

In [48]:
A.size

6

In [49]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

B.shape prints (2, 2, 3)
first 2 -> no. of blocks
(2, 3) is order
order must be same in all blocks
if the shape isn't consistent, it'll just fall back to regular Python objects

In [50]:
B.shape

(2, 2, 3)

In [51]:
B.ndim

3

In [52]:
B.size

12

In [55]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Indexing & Slicing of Matrices

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [61]:
A[1]

array([4, 5, 6])

In [63]:
A[1][0]

np.int64(4)

In [68]:
A[1, 0]

np.int64(4)

In [69]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [72]:
A[:2, 2:]

array([[3],
       [6]])

In [73]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

NumPy arrays are mutable.

In [74]:
A[1] = np.array([10, 10, 10])

In [75]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [76]:
A[2] = 99

In [77]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary Statistics

In [78]:
a = np.array([1, 2, 3, 4])

In [79]:
a.sum()

np.int64(10)

In [80]:
a.mean()

np.float64(2.5)

In [81]:
a.std()

np.float64(1.118033988749895)

In [82]:
a.var()

np.float64(1.25)

In [83]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [84]:
A.sum()

np.int64(45)

In [85]:
A.mean()

np.float64(5.0)

In [86]:
A.std()

np.float64(2.581988897471611)

In [87]:
A.sum(axis=0)

array([12, 15, 18])

In [88]:
A.sum(axis=1)

array([ 6, 15, 24])

In [90]:
A.mean(axis=0)

array([4., 5., 6.])

In [92]:
A.mean(axis=1)

array([2., 5., 8.])

In [94]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [95]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized Operations

In [106]:
a = np.arange(4)

In [97]:
a

array([0, 1, 2, 3])

In [107]:
a + 10

array([10, 11, 12, 13])

In [108]:
a * 10

array([ 0, 10, 20, 30])

In [109]:
a

array([0, 1, 2, 3])

In [110]:
a += 100

In [111]:
a

array([100, 101, 102, 103])

In [112]:
l = [0, 1, 2, 3]

In [113]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [114]:
a = np.arange(4)

In [115]:
a

array([0, 1, 2, 3])

In [116]:
b = np.array([10, 10, 10, 10])

In [117]:
a + b

array([10, 11, 12, 13])

In [118]:
a * b

array([ 0, 10, 20, 30])

Boolean Arrays

In [119]:
a = np.arange(4)

In [120]:
a

array([0, 1, 2, 3])

In [121]:
a[[True, False, False, True]]

array([0, 3])

In [122]:
a >= 2

array([False, False,  True,  True])

In [123]:
a[a >= 2]

array([2, 3])

In [124]:
a.mean()

np.float64(1.5)

In [126]:
a[a > a.mean()]

array([2, 3])

In [127]:
a[~(a > a.mean())]

array([0, 1])

In [128]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [129]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [130]:
A = np.random.randint(100, size=(3, 3))

In [131]:
A

array([[95, 37, 81],
       [69, 56, 39],
       [92, 61, 54]], dtype=int32)

In [132]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([95, 81, 56, 92, 54], dtype=int32)

In [133]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [137]:
A[A > 30]

array([95, 37, 81, 69, 56, 39, 92, 61, 54], dtype=int32)

In [136]:
A[True]

array([[[95, 37, 81],
        [69, 56, 39],
        [92, 61, 54]]], dtype=int32)

Linear Algebra

In [138]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [139]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [140]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [145]:
# Multiplication
(A @ B).shape

(3, 2)

In [ ]:
# Transpose of a Matrix
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [146]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory

Int, floats

In [148]:
# An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [149]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [150]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [151]:
np.dtype(float).itemsize

8

Lists are even larger

In [152]:
# A one-element list
sys.getsizeof([1])

64

In [154]:
# An array of one element in numpy
np.array([1]).nbytes

8

And performance is also important

In [155]:
l = list(range(1000))

In [156]:
a = np.arange(1000)

In [157]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 192 μs


np.int64(332833500)

In [158]:
%time sum([x  ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 217 μs


332833500

Useful NumPy functions

random

In [159]:
np.random.random(size=2)

array([0.8125846 , 0.26494683])

In [160]:
np.random.normal(size=2)

array([-0.01939806, -0.31663382])

In [161]:
np.random.rand(2, 4)

array([[0.94004222, 0.25690633, 0.89998176, 0.29663908],
       [0.22895917, 0.9482124 , 0.35102972, 0.9301152 ]])

arange

In [162]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [164]:
np.arange(0, 1, -1)

array([], dtype=int64)

reshape

In [165]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [166]:
np.arange(10).reshape(5,  2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [ ]:
# 0 se 1 ke darmiyan 5 equally spaced numbers generate karo.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [169]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [170]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [171]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [172]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [173]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [174]:
np.ones(3)

array([1., 1., 1.])

In [175]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [176]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [181]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [178]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [182]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [183]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [184]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [185]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [186]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [187]:
"Hello World"[6]

'W'